development:
  adapter: postgresql
  database: loop_development
  host: localhost

test:
  adapter: postgresql
  database: loop_test
  host: localhost

production:
  adapter: postgresql
  database: loop_production
  host: localhost
